name: 'Quasar Play Store'
description: 'Connect your GitHub Action workflow to Play Store'
branding:
  icon: 'airplay'
  color: 'gray-dark'
inputs:
  play_store_credentials:
      description: 'Play Store Credentials'
      default: ''
      required: true
  app_version:
      description: 'App Version'
      default: ''
      required: true
    package_name:
      description: 'Package Name'
      default: ''
      required: true
    alias:
      description: 'Secrets Alias'
      default: ''
      required: true
    key_store_password:
      description: 'Secrets Key Store Password'
      default: ''
      required: true
    app_track:
      description: 'App Track'
      default: 'internal'
      required: true
    build_tools_version:
      description: 'Build Tools Version'
      default: '33.0.2'
      required: true
    node_version:
      description: 'Node Version'
      default: '18'
      required: true
runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v3
      - name: Generate Base64 Release Key
        shell: bash
        run: |
          echo "KEYSTORE_BASE64=$(openssl base64 < ${{ inputs.keystore_file }} | tr -d '\n')" >> "$GITHUB_OUTPUT"
      
