name: 'Quasar Play Store'
description: 'Connect your GitHub Action workflow to Play Store'
branding:
  icon: 'airplay'
  color: 'gray-dark'
inputs:
  play_store_credentials:
      description: 'Play Store Credentials'
      default: ''
      required: true
runs:
    steps:
      - name: Check Runner OS
        if: ${{ runner.os != 'Linux' }}
        shell: bash
        run: |
          echo "::error title=⛔ error hint::Support Linux Only"
          exit 1
