name: 'Quasar Play Store'
description: 'Connect your GitHub Action workflow to Play Store'
author: 'Anant Negi'
branding:
  icon: 'airplay'
  color: 'gray-dark'
inputs:
  play_store_credentials:
      description: 'Play Store Credentials Base Encoded'
      default: ''
      required: true
  app_version:
      description: 'App Version'
      default: ''
      required: true
  package_name:
      description: 'Package Name'
      default: ''
      required: true
  keystore_base64:
      description: 'Keystore File Base Encoded'
      default: ''
      required: true
  alias:
      description: 'Secrets Alias'
      default: ''
      required: true
  key_store_password:
      description: 'Secrets Key Store Password'
      default: ''
      required: true
  app_track:
      description: 'App Track'
      default: 'internal'
      required: true
  build_tools_version:
      description: 'Build Tools Version'
      default: '33.0.2'
      required: true
  node_version:
      description: 'Node Version'
      default: '18'
      required: true
  create_release_tags:
      description: 'Create Release Tags'
      default: true
      required: false
  create_release:
      description: 'Create Release'
      default: true
      required: false
  delete_workflow:
      description: 'Delete Workflow Files'
      default: true
      required: false
env:
  APP_VERSION: ""
  KEYSTORE_DECODE64: ""
  PLAY_STORE_CREDENTIALS: ""
runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v3

      - name: Delete List of worflows - Status by Failure
        if: ${{ inputs.delete_workflow == true }}
        uses: actions/github-script@v6
        with:
          script: |
            const full_repo = '${{ github.repository }}'.split('/')
            const owner_name = full_repo[0]
            const repo_name = full_repo[1]
            const failedWorkflowRuns = await github.rest.actions.listWorkflowRunsForRepo({
              owner: owner_name,
              repo: repo_name,
              status: 'failure',
              per_page: 100,
            });
            for (const workflowRun of failedWorkflowRuns.data.workflow_runs) {
              await github.rest.actions.deleteWorkflowRun({
                owner: owner_name,
                repo: repo_name,
                run_id: workflowRun.id,
              });
              console.log(`Deleted workflow run ${workflowRun.id}.`);
            }
            const cancelledWorkflowRuns = await github.rest.actions.listWorkflowRunsForRepo({
                owner: owner_name,
                repo: repo_name,
                status: 'failure',
                per_page: 100,
              });
              for (const workflowRun of cancelledWorkflowRuns.data.workflow_runs) {
                await github.rest.actions.deleteWorkflowRun({
                  owner: owner_name,
                  repo: repo_name,
                  run_id: workflowRun.id,
                });
                console.log(`Deleted workflow run ${workflowRun.id}.`);
              }
            const skippedWorkflowRuns = await github.rest.actions.listWorkflowRunsForRepo({
                owner: owner_name,
                repo: repo_name,
                status: 'failure',
                per_page: 100,
              });
              for (const workflowRun of skippedWorkflowRuns.data.workflow_runs) {
                await github.rest.actions.deleteWorkflowRun({
                  owner: owner_name,
                  repo: repo_name,
                  run_id: workflowRun.id,
                });
                console.log(`Deleted workflow run ${workflowRun.id}.`);
              }
      - name: Generate Base64 Release Key
        shell: bash
        run: |
          echo "PLAY_STORE_CREDENTIALS=$(${{ inputs.play_store_credentials }} | base64 --decode | tr -d '\n')" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}  # Adjust this to your desired Node.js version
      - name: Append v in APP_VERSION
        shell: bash
        run: |
          echo APP_VERSION="v${{ inputs.app_version }}" >> "$GITHUB_ENV"
      - name: Inputs Print
        shell: bash
        run: |
          echo "Package Name: ${{ inputs.package_name }}"
          echo "App Version: ${{ env.APP_VERSION }}"
          echo "Track: ${{ inputs.app_track }}"
          echo "Bundle Tools Version: ${{ inputs.build_tools_version }}"
      - uses: actions/cache@v3
        with:
          key: node-dependencies
          path: node_modules
      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: |
          yarn global add @quasar/cli
          yarn global add cordova
          yarn install
      - name: Build Mobile Builder
        shell: bash
        run: quasar build -m cordova -T android
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: src-cordova/platforms/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ inputs.keystore_base64 }}
          alias: ${{ inputs.alias }}
          keyStorePassword: ${{ inputs.key_store_password }}
        env:
          BUILD_TOOLS_VERSION: ${{ inputs.build_tools_version }}
      - uses: actions/upload-artifact@v3
        with:
          name: $ - $ - $ - App bundle(s) AAB release generated
          path: $/build/outputs/bundle/release/
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: $PLAY_STORE_CREDENTIALS
          track: ${{ inputs.app_track }}
          packageName: ${{ inputs.package_name }}
          releaseName: ${{ env.APP_VERSION }}
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          debugSymbols: src-cordova/platforms/android/app/build/intermediates/merged_native_libs/release/out/lib

      - name: Create tags
        if: ${{ inputs.create_release_tags == true }}
        uses: actions/github-script@v5
        with:
          script: |
            const tags = [
              $APP_VERSION
            ];

            tags.forEach((tag) => {
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tag}`,
                sha: context.sha
              })
            })

      - name: Release
        if: ${{ inputs.create_release == true }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $APP_VERSION
          prerelease: false
          generate_release_notes: true
          draft: false     