name: Upload to Play Store
on:
  push:
    branches: [ test, main ]
  workflow_dispatch:
  
jobs:          
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Quasar Play Store
        uses: codeeshop-oc/quasar-playstore-github-action@1.0.4
        
        with:
          play_store_credentials: play-store-services.secret
          keystore_base64: my-release-key.keystore
          key_store_password: 'XXXXXXXXXX'
          app_version: '1.0.0'
          package_name: 'com.app_name.com'
          alias: 'alias_name'
          app_track: 'internal'
          build_tools_version: '33.0.2'
          node_version: '18'
          create_release_tags: false
          create_release: false

